"use client";

import Image from "next/image";
import { motion, useMotionValueEvent, useScroll } from "motion/react";
import { useState } from "react";
import { track } from "@/lib/analytics";
import { IMAGES } from "@/lib/generated/images";
import { SITE } from "@/lib/site";
import { ButtonLink } from "./Button";

const logo = IMAGES["logo-ink.png"];

type NavLink = { label: string; href: string };

/**
 * Sticky nav that starts transparent over the hero and settles into a
 * frosted ivory bar once the user scrolls, so the hero image is never
 * cropped by a solid header on first paint.
 */
export function Nav({ links }: { links: NavLink[] }) {
  const { scrollY } = useScroll();
  const [solid, setSolid] = useState(false);

  useMotionValueEvent(scrollY, "change", (y) => setSolid(y > 40));

  return (
    <motion.header
      initial={{ y: -24, opacity: 0 }}
      animate={{ y: 0, opacity: 1 }}
      transition={{ duration: 0.7, delay: 0.1, ease: [0.16, 1, 0.3, 1] }}
      className={`sticky top-0 z-60 transition-[background-color,border-color,backdrop-filter] duration-400 ${
        solid
          ? "border-b border-ink/12 bg-ivory/92 backdrop-blur-[12px]"
          : "border-b border-transparent bg-transparent"
      }`}
    >
      <div className="shell flex h-(--nav-h) items-center justify-between gap-6">
        {/* The supplied logo is white-on-transparent, so the nav uses the
            ink recolour generated by scripts/prepare-images.mjs. The
            footer, being dark, keeps the original white version. */}
        <a href="#top" className="flex items-center no-underline" aria-label={`${SITE.doctor} — home`}>
          <Image
            src={logo.src}
            alt={`${SITE.doctor}, Cirujano Plástico`}
            width={logo.width}
            height={logo.height}
            priority
            className="h-auto w-[124px] sm:w-[142px] lg:w-[152px]"
          />
        </a>

        <nav className="hidden items-center gap-8 lg:flex">
          {links.map((l) => (
            <a
              key={l.href}
              href={l.href}
              className="group relative text-[14px] font-medium text-body no-underline transition-colors duration-250 hover:text-gold"
            >
              {l.label}
              <span className="absolute -bottom-1 left-0 h-px w-full origin-left scale-x-0 bg-gold transition-transform duration-350 ease-[cubic-bezier(0.16,1,0.3,1)] group-hover:scale-x-100" />
            </a>
          ))}
        </nav>

        <div className="flex items-center gap-3">
          {/* The number in the nav opens WhatsApp, not a dialler — that is
              the channel the clinic wants these going to. External, so it
              needs rel="noopener noreferrer" with the target; the audit
              flags a bare target="_blank". */}
          <a
            href={SITE.whatsappHref}
            target="_blank"
            rel="noopener noreferrer"
            onClick={() => track("whatsapp_click", { label: "nav" })}
            className="hidden text-[14px] font-medium text-body no-underline transition-colors hover:text-gold md:inline lg:hidden xl:inline"
          >
            {SITE.contactDisplay}
          </a>
          {/* Hidden on the smallest screens — the sticky bottom bar owns
              the CTA there and two competing buttons hurt conversion.
              The visibility class sits on a wrapper because the button's
              own `inline-flex` would otherwise beat `hidden`: both are
              display utilities of equal specificity, so source order in
              the stylesheet decides, not the order in the attribute. */}
          <div className="hidden sm:block">
            <ButtonLink href="#book" size="sm" event="cta_click" eventLabel="nav">
              Book a consultation
            </ButtonLink>
          </div>
        </div>
      </div>
    </motion.header>
  );
}
